#!/usr/bin/env bash
# Installs nginx, sets it up to listen on port 80 and creates a landing page

#updates apt repo
sudo apt-get update -y
sudo apt-get upgrade -y

# Installs nginx
sudo apt-get install nginx -y

#starts the server
sudo service nginx start

#creates the index file
echo "Hello World" > /var/www/html/index.nginx-debian.html