#!/usr/bin/env bash
# This script cycles through hrs and mins

hr=0
while ((hr<12));do
    echo "Hour: $hr"
    min=1
    while ((min<60));do
        echo "$min"
        ((min++))
    done
    ((hr++))
done
echo "Hour: 12"
