#!/usr/bin/env bash
#Starts nginx as the nginx user
sudo chmod 006 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
